######################################################################
# Automatically generated by qmake (2.01a) ?? 7? 1 11:07:43 2017
######################################################################

TEMPLATE = app
TARGET = NN_UI_R1 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += \
	NN_plotter.h \
	DotMatrixEditor.h \
	ImageViewSetting.h

SOURCES += main.cpp \
	NN_plotter.cpp \
	DotMatrixEditor.cpp

RESOURCES += NN_plotter.qrc 

